version: '3'

services:
  web:
    build: .
    container_name: django_rule_engine_app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
